<template>
    <div>
                                <h3 class="report-heading">INDIVIDUAL REPORTS</h3>
                                <div class="alert alert-light alert-dismissible fade show" role="alert">
                                    Guideline: 1 for C.O, 1 for R.O and retain 1 File Copy.
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="row mt-3">
                                    <div class="col-md-3">
                                        <div class="card card-border-user shadow">
                                            <div class="card-body box-report">
                                                <div class="text-center">
                                                    <h6>Individual Performance Report (IPR)</h6>
                                                </div>
                                            </div>
                                            <br>
                                            <div class="col-md-12 text-right mb-3">
                                                <a href="/reports/individual-performance-report" target="_blank"><button type="button" class="btn btn-success d-inline float-right">
                                                    View <view-icon></view-icon>
                                                </button></a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="card card-border-user shadow">
                                            <div class="card-body box-report">
                                                <div class="text-center">
                                                    <h6>Individual Report CICL</h6><br>
                                                </div>
                                            </div>
                                            <br>
                                            <div class="col-md-12 text-right mb-3">
                                                <a href="/reports/individual-report-cicl" target="_blank"><button type="button" class="btn btn-success d-inline float-right">
                                                    View <view-icon></view-icon>
                                                </button></a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="card card-border-user shadow">
                                            <div class="card-body box-report">
                                                <div class="text-center">
                                                    <h6>Inquest Report</h6><br>
                                                </div>
                                            </div>
                                            <br>
                                            <div class="col-md-12 text-right mb-3">
                                                <a href="/reports/inquest-report" target="_blank"><button type="button" class="btn btn-success d-inline float-right">
                                                    View <view-icon></view-icon>
                                                </button></a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="card card-border-user shadow">
                                            <div class="card-body box-report">
                                                <div class="text-center">
                                                    <h6>List of Detainees Represented in Court</h6>
                                                </div>
                                            </div>
                                            <br>
                                            <div class="col-md-12 text-right mb-3">
                                                <a href="/reports/list-detainees-represented-court" target="_blank"><button type="button" class="btn btn-success d-inline float-right">
                                                    View <view-icon></view-icon>
                                                </button></a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="card card-border-user shadow">
                                            <div class="card-body box-report">
                                                <div class="text-center">
                                                    <h6>List of Favorable Decisions-Dispositions</h6>
                                                </div>
                                            </div>
                                            <br>
                                            <div class="col-md-12 text-right mb-3">
                                                <a href="/reports/list-favorable-decision-dispositions" target="_blank"><button type="button" class="btn btn-success d-inline float-right">
                                                    View <view-icon></view-icon>
                                                </button></a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="card card-border-user shadow">
                                            <div class="card-body box-report">
                                                <div class="text-center">
                                                    <h6>Documents Notarized<br><br></h6>
                                                </div>
                                            </div>
                                            <br>
                                            <div class="col-md-12 text-right mb-3">
                                                <a href="/reports/document-notarized" target="_blank"><button type="button" class="btn btn-success d-inline float-right">
                                                    View <view-icon></view-icon>
                                                </button></a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="card card-border-user shadow">
                                            <div class="card-body box-report">
                                                <div class="text-center">
                                                    <h6>Report on Victim's Case Handles<br><br></h6>
                                                </div>
                                            </div>
                                            <br>
                                            <div class="col-md-12 text-right mb-3">
                                                <a href="/reports/report-victims-cases-handled" target="_blank"><button type="button" class="btn btn-success d-inline float-right">
                                                    View <view-icon></view-icon>
                                                </button></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <h3 class="mt-5 report-heading">INVENTORY REPORTS</h3>
                                <div class="alert alert-light alert-dismissible fade show" role="alert">
                                    Guideline: Send to Public Head Attorney of PAO District.
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="row mt-3">
                                    <div class="col-md-3">
                                        <div class="card card-border-user shadow">
                                            <div class="card-body box-report">
                                                <div class="text-center">
                                                    <h6>Monthly Inventory of Cases</h6>
                                                </div>
                                            </div>
                                            <br>
                                            <div class="col-md-12 text-right mb-3">
                                                <a href="/reports/monthly-inventory-cases" target="_blank"><button type="button" class="btn btn-success d-inline float-right">
                                                    View <view-icon></view-icon>
                                                </button></a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="card card-border-user shadow">
                                            <div class="card-body box-report">
                                                <div class="text-center">
                                                    <h6>Monthly Inventory of Client Served</h6>
                                                </div>
                                            </div>
                                            <br>
                                            <div class="col-md-12 text-right mb-3">
                                                <a href="/reports/monthly-inventory-client-served" target="_blank"><button type="button" class="btn btn-success d-inline float-right">
                                                    View <view-icon></view-icon>
                                                </button></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
</template>

<script>
    export default {
        mounted() {
        }
    }
</script>
